RMADA_enable: true
RMADA_sharpenweight: 0
RMADA_edge_detection_sharpening: 3
RMADA_wavelet_sharpening: 1
RMADA_adaptive_sharpened: 0
RMADA_contrast: 0.22
RMADA_brightness: -0.18
RMADA_saturation: 0.05
RMADA_gamma: 1.2
RMADA_noise: 0.015
RMADA_vignette: 0.05
RMADA_translate: true
RMADA_translate_lang: es
RMADA_translate_mode: Full translate
RMADA_fixhr: true
RMADA_removeloras: false
RMADA_removeemphasis: false
RMADA_fixprompt: true
RMADA_moveloras: true
RMADA_copyright: 'MODEL: {CHECKPOINT} | SAMPLER: {SAMPLER} | STEPS: {STEPS} | CFG
  Scale: {CFG} | WIDTH: {WIDTH} | HEIGHT: {HEIGHT}     -       @RMADA''24'
RMADA_loras: true
RMADA_CheckSharpen: true
RMADA_CheckEnhance: true
RMADA_CheckFilters: true
RMADA_CheckCopyright: true
RMADA_SaveBefore: false
RMADA_lora_1_check: false
RMADA_lora_1: RMSDXL_Enhance
RMADA_lora_1_weight: 0
RMADA_lora_1_text: ''
RMADA_lora_2_check: false
RMADA_lora_2: RMSDXL_Creative
RMADA_lora_2_weight: 0
RMADA_lora_2_text: ''
RMADA_lora_3_check: false
RMADA_lora_3: RMSDXL_Darkness_Cinema
RMADA_lora_3_weight: 0
RMADA_lora_3_text: darkness cinema
RMADA_lora_4_check: false
RMADA_lora_4: RMSDXL_Photo
RMADA_lora_4_weight: 0
RMADA_lora_4_text: photo realistic
RMADA_lora_5_check: false
RMADA_lora_5: None
RMADA_lora_5_weight: 0
RMADA_lora_5_text: ''
